spring.application.name=APIExamenTecnico
MONGODB_USERNAME=maalaagasz_db_user
MONGODB_PASSWORD=7Ceto3pzTZCtxrFE
MONGODB_CLUSTER=cluster0.vbvl5pp
MONGODB_DB_NAME=sample_mflix

# Opción 1 (Estándar Spring Boot 2.x / 3.x)
spring.data.mongodb.uri=mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_CLUSTER}.mongodb.net/${MONGODB_DB_NAME}?retryWrites=true&w=majority

# Opción 2 (Sintaxis simplificada / legacy)
spring.mongodb.uri=mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_CLUSTER}.mongodb.net/${MONGODB_DB_NAME}?retryWrites=true&w=majority

server.port=8080
